#pragma once

void test_gamenode_undying_rune_applies_buff_at_rune_load_5();
void test_gamenode_undying_buff_expires_after_15_seconds();
void test_gamenode_undying_buff_reapplied_after_cooldown_expires();
